server.port=8080

spring.application.name=wecom-scrm-server

spring.datasource.dynamic.primary=master
spring.datasource.dynamic.strict=false
spring.datasource.dynamic.datasource.master.url=jdbc:mysql://127.0.0.1:3306/wecom_scrm_master?useUnicode=true&characterEncoding=utf8&createDatabaseIfNotExist=true
spring.datasource.dynamic.datasource.master.username=root
spring.datasource.dynamic.datasource.master.password=123456
spring.datasource.dynamic.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.dynamic.datasource.master.max-idle=10
spring.datasource.dynamic.datasource.master.max-wait=1000
spring.datasource.dynamic.datasource.master.min-idle=5
spring.datasource.dynamic.datasource.master.initial-size=5

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Logging Configuration
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# Redis Configuration (Will be started by EmbeddedRedisConfig)
spring.redis.host=localhost
spring.redis.port=6379

# Externalized Secrets
spring.config.import=optional:classpath:secret.properties